### ISSUE TITLE
Program Reads Incorrect File Name

### ISSUE THREAD

**Issue by Bomb-Bard** [ramzialhaddadtm/discord-data-package-viewer-parser#7]
After running Main.exe and progressing to the main window, I clicked Find Stuff. This succeeded, and presented me with a list of all my contacts. Upon clicking on one though, the program crashed, citing an error at line 113, under findAllTheChats. I looked into it myself, and it appears that it's a fileRead error caused by the program trying to read in "messages/(number)/messages.csv", but Discord chat logs are prefixed by the letter "c" now, presumably to denote a chat. So it _should_ be trying to read in "messages/c(number)/messages.csv"

**The fix is incredibly simple** - change line 113 from
df = pandas.read_csv("messages/"+zz+"/messages.csv")
to
df = pandas.read_csv("messages/c"+zz+"/messages.csv")

I tested this by removing the "c" prefix from one of my chats, and the issue no longer occurred with that particular chat.

**Comment by EnderShadowborne** [comment]
What file are you referring to where one should make these changes, might I ask?

**Comment by Bomb-Bard** [comment]
main.py

**Comment by EnderShadowborne** [comment]
I don't see that anywhere in my build folder, or I guess I should be downloading the source code and then trying to figure out how to run it on a Windows

**Comment by Bomb-Bard** [comment]
Yes, my issue was found on a Windows PC. I found the issue just by looking at the code page of this repo and investigating main.py.

**Comment by EnderShadowborne** [comment]
Have you got it to work since? Is there an easier way to mass rename the files so they otherwise keep their numerical names, just the "c" omitted?

**Comment by Bomb-Bard** [comment]
It wasn't incredibly urgent for me, so I didn't bother, but I could probably write up a tiny bit of code to go through and mass rename them. Would definitely be easier if the source code just accepted file names both with and without a preceding "c". If you're wanting to implement that, in Python I'd just use try/except with the base file name, then again with a preceding c. If either exception gets caught just alert the user that the filename is incorrect.

**Comment by EnderShadowborne** [comment]
I dunno how to do that, I'm no coder myself, really...

**Comment by Bomb-Bard** [comment]
It's really not too bad. Consider you're approaching the point in the code where you're about to open your file. You have a var (in our case "zz") that holds the file name we want to open. Instead of just using 
`df = pandas.read_csv("messages/"+zz+"/messages.csv")`
You'd want to first start a "try" block, which attempts to run a piece of code, and if it would throw an error (i.e. because of an incorrect file name) you can control what happens next instead of your code automatically stopping. Thus, we'd instead want:
```py
try:
    df = pandas.read_csv("messages/"+zz+"/messages.csv")
except:
    #This is the part that runs if it can't read the file name without the c.
    try:
        df = pandas.read_csv("messages/c"+zz+"/messages.csv")
    except:
        #This is the part that runs if it can't read the file name even _with_ the c.
        print(f"Couldn't read file name {zz}. Check and make sure it's correct.")
```

**Comment by EnderShadowborne** [comment]
Firstly, should I download the source code? If so, I'll need to know...

Otherwise I won't know what to do with this...

**Comment by Bomb-Bard** [comment]
You'll need to download the source code and modify main.py with my suggested changes. Past that, you'll need to research how to build the program with the new python file. I can't really walk you through it step-by-step, but there are plenty of online tutorials on how to manage python graphical projects.

**Comment by EnderShadowborne** [comment]
Alright, got it converted to exe, but I feel like something isn't quite right... aren't there supposed to be these other folders and stuff? Or is it not necessary?

**Comment by Bomb-Bard** [comment]
If it runs, then you've got it figured out. If it doesn't, then it's back to the drawing board. I assume you packaged all the files into the .exe, so hopefully it'll be the former option.

**Comment by EnderShadowborne** [comment]
I used auto-py-to-exe

**Comment by Bomb-Bard** [comment]
All you can do is try and run it and see what happens. From there it's just the process of debugging.

**Comment by EnderShadowborne** [comment]
It just opens and immediately closes, otherwise doing nothing

**Comment by Bomb-Bard** [comment]
Welcome to programming! I'd recommend running it out of a terminal so you get a proper error message. I assume your auto-py-to-exe didn't package the UI, either, so you'll need to figure out how the original poster did that. Again, I can't walk you through it. Programming is 80% googling an issue, 10% coding, and 10% wondering what on earth is even broken. You'll just have to work through it!

**Comment by EnderShadowborne** [comment]
Nope, and I don't have a terminal besides the python terminal, if that helps...

**Comment by EnderShadowborne** [comment]
Ran it in CMD, and I got... well... SOMETHING

`87878 ERROR: An error occurred while packaging
Traceback (most recent call last):
  File "C:\Users\DUDEA\AppData\Local\Programs\Python\Python311\Lib\site-packages\auto_py_to_exe\packaging.py", line 131, in package
    run_pyinstaller()
  File "C:\Users\DUDEA\AppData\Local\Programs\Python\Python311\Lib\site-packages\PyInstaller\__main__.py", line 180, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "C:\Users\DUDEA\AppData\Local\Programs\Python\Python311\Lib\site-packages\PyInstaller\__main__.py", line 61, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "C:\Users\DUDEA\AppData\Local\Programs\Python\Python311\Lib\site-packages\PyInstaller\building\build_main.py", line 977, in main
    build(specfile, distpath, workpath, clean_build)
  File "C:\Users\DUDEA\AppData\Local\Programs\Python\Python311\Lib\site-packages\PyInstaller\building\build_main.py", line 899, in build
    exec(code, spec_namespace)
  File "C:\Users\DUDEA\AppData\Local\Temp\tmpn9pmok3i\discord-data-package-viewer-parser-master.spec", line 7, in <module>
    a = Analysis(
        ^^^^^^^^^
  File "C:\Users\DUDEA\AppData\Local\Programs\Python\Python311\Lib\site-packages\PyInstaller\building\build_main.py", line 412, in __init__
    self.__postinit__()
  File "C:\Users\DUDEA\AppData\Local\Programs\Python\Python311\Lib\site-packages\PyInstaller\building\datastruct.py", line 173, in __postinit__
    self.assemble()
  File "C:\Users\DUDEA\AppData\Local\Programs\Python\Python311\Lib\site-packages\PyInstaller\building\build_main.py", line 575, in assemble
    priority_scripts.append(self.graph.add_script(script))
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DUDEA\AppData\Local\Programs\Python\Python311\Lib\site-packages\PyInstaller\depend\analysis.py", line 269, in add_script
    self._top_script_node = super().add_script(pathname)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DUDEA\AppData\Local\Programs\Python\Python311\Lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1415, in add_script
    with open(pathname, 'rb') as fp:
         ^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\DUDEA\\Downloads\\Discord Package stuff\\discord-data-package-viewer-parser-master'`

**Comment by jonahbrawley** [comment]
This program isn't exactly feature-rich, but I implemented that fix and made a build as well as added building instructions on a fork @EnderShadowborne 

https://github.com/jonahbrawley/discord-data-package-viewer-parser
